// Nội dung mẫu — thay bằng thông số/giá thật qua trang Admin > Sản phẩm.
const img = (slug) => [`/img/products/${slug}-1.svg`, `/img/products/${slug}-2.svg`];

const COMMON_SAFETY = [
  'Tự ngắt khi không có nồi hoặc nồi không phù hợp',
  'Khóa trẻ em — chạm giữ 3 giây để khóa/mở',
  'Cảnh báo mặt bếp còn nóng (H) sau khi tắt',
  'Bảo vệ quá nhiệt, quá áp và chống sụt áp',
];

const products = [
  {
    slug: 'prochef-s1-compact',
    name: 'ProChef S1 Compact',
    sku: 'MX-S1',
    line: 'don',
    tagline: 'Nhỏ gọn cho căn hộ và bữa ăn nhanh',
    short_desc: 'Bếp từ đơn 2000W, 6 chế độ nấu cài sẵn, hẹn giờ đến 4 giờ. Gọn nhẹ 2,3 kg — cất tủ hay mang đi đều tiện.',
    description:
      'ProChef S1 Compact là lựa chọn khởi đầu hoàn hảo cho căn hộ nhỏ, phòng trọ hay làm bếp phụ bên cạnh bếp chính. Công suất 2000W đủ để đun sôi 1,5 lít nước trong khoảng 4 phút, trong khi 8 mức công suất giúp bạn chủ động từ hâm nóng đến xào lửa lớn.\n\n' +
      'Sáu chế độ cài sẵn — lẩu, xào, chiên, nấu nước, hầm, hâm nóng — giúp bạn chỉ cần một chạm. Mặt kính ceramic phẳng, lau sạch trong vài giây, không bám dầu mỡ như bếp gas.',
    price: 1290000,
    compare_price: 1590000,
    stock: 120,
    power_w: 2000,
    zones: 1,
    badge: 'Bán chạy',
    highlights: ['2000W', '8 mức công suất', 'Hẹn giờ 4 giờ'],
    specs: [
      ['Loại bếp', 'Bếp từ đơn'],
      ['Công suất', '2000W'],
      ['Điện áp', '220V – 50Hz'],
      ['Mặt bếp', 'Kính ceramic chịu nhiệt'],
      ['Điều khiển', 'Cảm ứng'],
      ['Mức công suất', '8 mức'],
      ['Hẹn giờ', '1 phút – 4 giờ'],
      ['Kích thước', '280 × 350 × 60 mm'],
      ['Trọng lượng', '2,3 kg'],
      ['Bảo hành', '12 tháng'],
    ],
    features: ['6 chế độ nấu cài sẵn', ...COMMON_SAFETY],
    images: img('prochef-s1-compact'),
    is_featured: true,
    sort_order: 1,
  },
  {
    slug: 'prochef-s2-slim',
    name: 'ProChef S2 Slim',
    sku: 'MX-S2',
    line: 'don',
    tagline: 'Mỏng 45 mm, thanh trượt cảm ứng',
    short_desc: 'Thiết kế siêu mỏng 45 mm với thanh trượt cảm ứng, 10 mức công suất và chế độ giữ ấm tự động.',
    description:
      'S2 Slim được thiết kế cho những gian bếp đề cao thẩm mỹ. Thân bếp chỉ dày 45 mm, viền bo mềm và thanh trượt cảm ứng cho phép tăng giảm lửa mượt mà như chỉnh âm lượng.\n\n' +
      'Chế độ giữ ấm tự động duy trì món ăn ở khoảng 70°C mà không làm khô hay cháy đáy — rất hợp cho bữa tối gia đình khi mọi người về không cùng giờ.',
    price: 1690000,
    compare_price: null,
    stock: 90,
    power_w: 2100,
    zones: 1,
    badge: 'Mới',
    highlights: ['Dày 45 mm', 'Thanh trượt cảm ứng', '10 mức công suất'],
    specs: [
      ['Loại bếp', 'Bếp từ đơn'],
      ['Công suất', '2100W'],
      ['Điện áp', '220V – 50Hz'],
      ['Mặt bếp', 'Kính ceramic chịu nhiệt'],
      ['Điều khiển', 'Thanh trượt cảm ứng'],
      ['Mức công suất', '10 mức'],
      ['Hẹn giờ', '1 phút – 3 giờ'],
      ['Kích thước', '290 × 360 × 45 mm'],
      ['Trọng lượng', '2,1 kg'],
      ['Bảo hành', '12 tháng'],
    ],
    features: ['Chế độ giữ ấm 70°C', 'Quạt tản nhiệt êm < 45 dB', ...COMMON_SAFETY],
    images: img('prochef-s2-slim'),
    is_featured: false,
    sort_order: 2,
  },
  {
    slug: 'prochef-s3-inverter',
    name: 'ProChef S3 Inverter',
    sku: 'MX-S3',
    line: 'don',
    tagline: 'Inverter — lửa nhỏ liên tục, không ngắt quãng',
    short_desc: 'Công nghệ Inverter 2200W cho lửa nhỏ ổn định, tiết kiệm điện đến 30%. Chế độ Boost đun sôi siêu tốc.',
    description:
      'Bếp từ thông thường giữ lửa nhỏ bằng cách bật – tắt liên tục, khiến nước dùng sôi không đều và món kho dễ cháy đáy. S3 Inverter điều chỉnh công suất liên tục, nhờ đó lửa nhỏ thực sự nhỏ và ổn định.\n\n' +
      'Chế độ Boost đẩy công suất lên tối đa trong 5 phút để đun sôi nhanh. Mạch Inverter giúp giảm hao phí điện năng tới 30% so với bếp từ cơ bản cùng công suất.',
    price: 2490000,
    compare_price: 2890000,
    stock: 60,
    power_w: 2200,
    zones: 1,
    badge: 'Inverter',
    highlights: ['Inverter 2200W', 'Tiết kiệm điện 30%', 'Chế độ Boost'],
    specs: [
      ['Loại bếp', 'Bếp từ đơn Inverter'],
      ['Công suất', '2200W (Boost)'],
      ['Điện áp', '220V – 50Hz'],
      ['Mặt bếp', 'Kính ceramic chịu nhiệt, chịu lực'],
      ['Điều khiển', 'Cảm ứng + thanh trượt'],
      ['Mức công suất', '12 mức'],
      ['Hẹn giờ', '1 phút – 4 giờ'],
      ['Kích thước', '300 × 380 × 55 mm'],
      ['Trọng lượng', '2,6 kg'],
      ['Bảo hành', '12 tháng'],
    ],
    features: ['Công nghệ Inverter lửa nhỏ liên tục', 'Chế độ Boost 5 phút', 'Cảm biến chống trào', ...COMMON_SAFETY],
    images: img('prochef-s3-inverter'),
    is_featured: true,
    sort_order: 3,
  },
  {
    slug: 'prochef-d5-duo',
    name: 'ProChef D5 Duo',
    sku: 'MX-D5',
    line: 'doi',
    tagline: 'Hai vùng nấu cho bữa cơm gia đình',
    short_desc: 'Bếp từ đôi 2 vùng từ 2000W + 2000W, lắp âm hoặc dương, 9 mức công suất mỗi vùng. Lựa chọn tối ưu chi phí.',
    description:
      'D5 Duo là bếp từ đôi dành cho gia đình 3 – 5 người: một vùng nấu canh, một vùng xào, mọi thứ lên bàn cùng lúc. Có thể lắp âm vào mặt đá hoặc đặt dương trên bàn bếp.\n\n' +
      'Mỗi vùng có 9 mức công suất và hẹn giờ độc lập. Bộ chia công suất thông minh giữ tổng công suất trong ngưỡng an toàn cho hệ thống điện gia đình.',
    price: 6990000,
    compare_price: 8490000,
    stock: 45,
    power_w: 4000,
    zones: 2,
    badge: 'Giá tốt',
    highlights: ['2 vùng từ 4000W', 'Lắp âm hoặc dương', 'Hẹn giờ từng vùng'],
    specs: [
      ['Loại bếp', 'Bếp từ đôi (từ + từ)'],
      ['Tổng công suất', '4000W'],
      ['Vùng trái', 'Từ 2000W – Ø 200 mm'],
      ['Vùng phải', 'Từ 2000W – Ø 200 mm'],
      ['Điện áp', '220V – 50Hz'],
      ['Mặt bếp', 'Kính ceramic chịu nhiệt'],
      ['Điều khiển', 'Cảm ứng'],
      ['Kích thước mặt', '730 × 430 mm'],
      ['Kích thước khoét đá', '680 × 380 mm'],
      ['Bảo hành', '36 tháng'],
    ],
    features: ['Lắp âm hoặc dương', 'Hẹn giờ độc lập từng vùng', 'Chia công suất thông minh', ...COMMON_SAFETY],
    images: img('prochef-d5-duo'),
    is_featured: true,
    sort_order: 4,
  },
  {
    slug: 'prochef-d7-inverter',
    name: 'ProChef D7 Inverter',
    sku: 'MX-D7',
    line: 'doi',
    tagline: 'Inverter hai vùng, Booster đun sôi siêu tốc',
    short_desc: 'Bếp từ đôi Inverter 2200W + 2200W, Booster, thanh trượt cảm ứng, cảm biến chống trào. Bảo hành 36 tháng.',
    description:
      'D7 Inverter mang lửa nhỏ ổn định của công nghệ Inverter lên cả hai vùng nấu — lý tưởng cho nồi nước dùng ninh nhiều giờ hay món kho cần liu riu.\n\n' +
      'Chế độ Booster đun sôi 2 lít nước trong khoảng 5 phút. Thanh trượt cảm ứng cho phép chỉnh lửa bằng một ngón tay, cảm biến chống trào tự hạ công suất khi nước tràn lên mặt kính.',
    price: 9490000,
    compare_price: 11290000,
    stock: 38,
    power_w: 4400,
    zones: 2,
    badge: 'Khuyên dùng',
    highlights: ['Inverter 2 vùng', 'Booster siêu tốc', 'Bảo hành 36 tháng'],
    specs: [
      ['Loại bếp', 'Bếp từ đôi Inverter'],
      ['Tổng công suất', '4400W'],
      ['Vùng trái', 'Từ Inverter 2200W – Ø 220 mm'],
      ['Vùng phải', 'Từ Inverter 2200W – Ø 200 mm'],
      ['Điện áp', '220V – 50Hz'],
      ['Mặt bếp', 'Kính ceramic chịu nhiệt, chịu lực'],
      ['Điều khiển', 'Thanh trượt cảm ứng'],
      ['Kích thước mặt', '750 × 450 mm'],
      ['Kích thước khoét đá', '690 × 390 mm'],
      ['Bảo hành', '36 tháng'],
    ],
    features: ['Inverter trên cả hai vùng', 'Booster đun sôi siêu tốc', 'Cảm biến chống trào', 'Tạm dừng nấu (Pause)', ...COMMON_SAFETY],
    images: img('prochef-d7-inverter'),
    is_featured: true,
    sort_order: 5,
  },
  {
    slug: 'prochef-d9-signature',
    name: 'ProChef D9 Signature',
    sku: 'MX-D9',
    line: 'doi',
    tagline: 'Phiên bản cao cấp nhất — kính vát cạnh, viền thép',
    short_desc: 'Bếp từ đôi cao cấp: Inverter 2 vùng 4600W, kính vát cạnh viền thép không gỉ, 15 mức công suất, bảo hành 36 tháng.',
    description:
      'D9 Signature là đỉnh cao của dòng ProChef. Mặt kính vát cạnh với viền thép không gỉ tạo điểm nhấn sang trọng cho gian bếp đá. Hai vùng Inverter với 15 mức công suất cho độ chính xác của bếp nhà hàng.\n\n' +
      'Vùng nấu lớn Ø 240 mm phù hợp chảo gang, nồi lẩu cỡ lớn. Chức năng Keep Warm, Pause và nhớ mức lửa gần nhất giúp nấu nướng liền mạch.',
    price: 12990000,
    compare_price: 14990000,
    stock: 25,
    power_w: 4600,
    zones: 2,
    badge: 'Cao cấp',
    highlights: ['Inverter 4600W', 'Kính vát cạnh viền thép', 'Bảo hành 36 tháng'],
    specs: [
      ['Loại bếp', 'Bếp từ đôi Inverter cao cấp'],
      ['Tổng công suất', '4600W'],
      ['Vùng trái', 'Từ Inverter 2400W – Ø 240 mm'],
      ['Vùng phải', 'Từ Inverter 2200W – Ø 200 mm'],
      ['Điện áp', '220V – 50Hz'],
      ['Mặt bếp', 'Kính ceramic vát cạnh, viền thép không gỉ'],
      ['Điều khiển', 'Thanh trượt cảm ứng, 15 mức'],
      ['Kích thước mặt', '770 × 450 mm'],
      ['Kích thước khoét đá', '700 × 400 mm'],
      ['Bảo hành', '36 tháng'],
    ],
    features: ['Vùng nấu lớn Ø 240 mm', 'Keep Warm & Pause', 'Nhớ mức lửa gần nhất', 'Cảm biến chống trào', ...COMMON_SAFETY],
    images: img('prochef-d9-signature'),
    is_featured: true,
    sort_order: 6,
  },
];

const coupons = [
  { code: 'PROCHEF10', type: 'percent', value: 10, min_order: 2000000, max_discount: 1000000 },
  { code: 'CHAOBAN200', type: 'fixed', value: 200000, min_order: 5000000, max_discount: null },
];

module.exports = { products, coupons };
